# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build SJTU Canvas executable

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build MacOS application
      run : |
        pyinstaller -n "SJTU Canvas下载器" -w --icon=resources/canvas.icns canvas_downloader.py
        mkdir -p dist/dmg
        cp -r dist/SJTU\ Canvas下载器.app dist/dmg
    - name: Create dmg
      run : |
        create-dmg \
        --volname "SJTU Canvas下载器" \
        --volicon "resources/canvas.icns" \
        --window-pos 200 120 \
        --window-size 600 300 \
        --icon-size 100 \
        --icon "SJTU Canvas下载器.app" 175 120 \
        --hide-extension "SJTU Canvas下载器.app" \
        --app-drop-link 425 120 \
        "dist/SJTU Canvas下载器.dmg" \
        "dist/dmg/"
